### PR TITLE
Standardising title format and content updates

### PR DESCRIPTION
**Pull request by nkoeries**

### CODE REVIEW

**Comment by arthurattwell** [comment]
@nkoeries Thanks. I've just checked your GitHub Pages, which is broken: https://nkoeries.github.io/learn-1/ I think this is because your repo name is not `learn`. I'll merge this in and debug locally. But you are going to need to rename your repo.

**Comment by nkoeries** [comment]
@arthurattwell I can't change the name because I still have the private repository linked to my account (thus the automatic suffix). Should I remove it from my account or is there another option?

screen shot 2018-02-13 at 20 24 14

**Comment by arthurattwell** [comment]
If all your recent changes are safely merged into the original repo now, you can simply 

1. delete your forks and local clones, 
2. fork `BettercareHealth/learn` again,
3. clone your fork.

**Comment by nkoeries** [comment]
@arthurattwell Just to be clear: I have to go into the Danger Zone under settings and delete both my repositories?

**Comment by arthurattwell** [comment]
@nkoeries Let's talk this through on a messenger rather than here.

**Pull request merged**
