### PR TITLE
Fix location of package

### PR DESCRIPTION
**Pull request by arthurattwell**
This may fix @nkoeries' problem described in #54.

### CODE REVIEW

**Comment by nkoeries** [comment]
ex-code updated. npm install complete. 
New issue: gulp not working. 
Noelles-Air:learn Noelle$ gulp --book infection-prevention-and-control

/Users/Noelle/Documents/Git/learn/node_modules/js-yaml/lib/js-yaml/loader.js:171
  throw generateError(state, message);
  ^
YAMLException: duplicated mapping key at line 22215, column -20370:
          web:
          ^
    at generateError (/Users/Noelle/Documents/Git/learn/node_modules/js-yaml/lib/js-yaml/loader.js:165:10)
    at throwError (/Users/Noelle/Documents/Git/learn/node_modules/js-yaml/lib/js-yaml/loader.js:171:9)
    at storeMappingPair (/Users/Noelle/Documents/Git/learn/node_modules/js-yaml/lib/js-yaml/loader.js:308:7)
    at readBlockMapping (/Users/Noelle/Documents/Git/learn/node_modules/js-yaml/lib/js-yaml/loader.js:1071:9)
    at composeNode (/Users/Noelle/Documents/Git/learn/node_modules/js-yaml/lib/js-yaml/loader.js:1332:12)
    at readBlockMapping (/Users/Noelle/Documents/Git/learn/node_modules/js-yaml/lib/js-yaml/loader.js:1062:11)
    at composeNode (/Users/Noelle/Documents/Git/learn/node_modules/js-yaml/lib/js-yaml/loader.js:1332:12)
    at readBlockSequence (/Users/Noelle/Documents/Git/learn/node_modules/js-yaml/lib/js-yaml/loader.js:928:5)
    at composeNode (/Users/Noelle/Documents/Git/learn/node_modules/js-yaml/lib/js-yaml/loader.js:1331:12)
    at readBlockMapping (/Users/Noelle/Documents/Git/learn/node_modules/js-yaml/lib/js-yaml/loader.js:1062:11)

**Comment by arthurattwell** [comment]
@nkoeries Believe it or not, that's great progress! The issue now is that there is a syntax error in your meta.yml. Probably a duplication of something around line 22215. Jekyll ignores duplicates, but the new gulp script can't and will throw errors.

**Comment by nkoeries** [comment]
@arthurattwell it seems that has been resolved.
New issue:
Noelles-Air:learn Noelle$ gulp --book -infection-prevention-and-control
If processing a translation's images, use the --language argument, e.g. gulp --language fr
[13:44:15] Using gulpfile ~/Documents/Git/learn/gulpfile.js
/usr/local/lib/node_modules/gulp/bin/gulp.js:129
    gulpInst.start.apply(gulpInst, toRun);
                   ^

TypeError: Cannot read property 'apply' of undefined
    at /usr/local/lib/node_modules/gulp/bin/gulp.js:129:20
    at process._tickCallback (internal/process/next_tick.js:61:11)
    at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)

**Comment by arthurattwell** [comment]
@nkoeries Might that one be because you've got an extra hyphen in there: `-infection-prevention-and-control`?

**Comment by nkoeries** [comment]
@arthurattwell: Same error coming up again.  
Noelles-Air:learn Noelle$ gulp --book infection-prevention-and-control
If processing a translation's images, use the --language argument, e.g. gulp --language fr
[14:07:54] Using gulpfile ~/Documents/Git/learn/gulpfile.js
/usr/local/lib/node_modules/gulp/bin/gulp.js:129
    gulpInst.start.apply(gulpInst, toRun);
                   ^

TypeError: Cannot read property 'apply' of undefined
    at /usr/local/lib/node_modules/gulp/bin/gulp.js:129:20
    at process._tickCallback (internal/process/next_tick.js:61:11)
    at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)

**Comment by arthurattwell** [comment]
@nkoeries Darn, okay. Let's connect on email to make a plan to debug in person.

**Pull request merged**
